### ISSUE TITLE
Hints in poem are inssuficient

### ISSUE THREAD

**Issue by ThePennitentOne** [sickthecat/crypto_challenge#1]
I tried to solve the poem in commit 57ea15c and the basic meaning is quite simple, but the commit message specifies 
 that there are multiple hints contained within, which is clearly indicating a bug in the poem since it only contains one hint

**Comment by sickthecat** [comment]
Poem was an artifact not used in the challenge, mistakenly uploaded. Although I agree with your assessment, it has been deleted. Closing issue.
